FROM node:14
WORKDIR /usr/src/app
ADD ./nodejsapp/package*.json /usr/src/app/
RUN npm install
ADD ./nodejsapp/node_modules /usr/src/app/
ADD ./nodejsapp/routes /usr/src/app/
ADD ./nodejsapp/views /usr/src/app/
ADD app.js /usr/src/app/
EXPOSE 8888
CMD [ "node", "app.js" ]
