FROM node:14
WORKDIR /usr/src/app
COPY ./package*.json /usr/src/app/
RUN npm install
COPY ./node_modules /usr/src/app/
COPY ./routes /usr/src/app/
COPY ./views /usr/src/app/
COPY app.js /usr/src/app/
EXPOSE 8888
CMD [ "node", "app.js" ]
