apiVersion: v1
kind: Pod
metadata:
  labels:
    npm-build: nodeapp
spec:
  containers:
  - name: docker
    image: docker:latest
    command:
    - cat
    tty: true
    volumeMounts:
      - mountPath: /var/run/docker.sock
        name: docker-sock
      - mountPath: /etc/docker
        name: docker-daemon
  volumes:
  - name: docker-sock
    hostPath:
     path: /var/run/docker.sock
  - name: docker-daemon
    hostPath:
     path: /etc/docker 
