apiVersion: v1
kind: Pod
metadata:
  labels:
    mvn-build: tomcat
spec:
  containers:
  - name: maven
    image: maven:3.8.6-jdk-11
    command:
    - cat
    tty: true
    volumeMounts:
      - mountPath: /etc/docker
        name: docker-daemon
  - name: docker
    image: docker:latest
    command:
    - cat
    tty: true
    volumeMounts:
      - mountPath: /var/run/docker.sock
        name: docker-sock
      - mountPath: /etc/docker
        name: docker-daemon
  volumes:
  - name: docker-sock
    hostPath:
     path: /var/run/docker.sock
  - name: docker-daemon
    hostPath:
     path: /etc/docker 
